fun main()
{
    println("Student Enrollment number: ")
    var sEnrollmentNumber=readLine()!!.toString()
    println("Student Name:")
    val name = readLine()!!.toString()
    println("Student Branch:")
    val branch = readLine()!!.toString()
    println("Student class name:")
    val classname = readLine()!!.toString()
    println("Student batch name:")
    val batchname = readLine()!!.toString()
    println("Student collage name:")
    val collagename = readLine()!!.toString()
    println("Student university name:")
    val universityname = readLine()!!.toString()
    println("Student age:")
    var age = readLine()!!.toInt()
    println("***********************")

    println("Student Enrollment No:”$sEnrollmentNumber")
    println("Student name: $name")
    println("Student Branch:$branch")
    println("Student class:$classname")
    println("Student Batch:$batchname")
    println("Student collage name:$collagename")
    println("Student university name:$universityname")
    println("Student age:$age")
}
